FROM openjdk:17-alpine AS final
FROM maven:3.8.3-openjdk-17 as build
COPY . ./code
RUN rm -rf /root/.m2
WORKDIR ./code
#RUN microdnf install iputils procps
# RUN sed -i '0,/localhost/s//172.19.0.3/' src/main/resources/application.properties \
#     && sed -i 's/localhost/172.19.0.2/' src/main/resources/application.properties \
#     && sed -i 's/localhost:3000/18.191.211.71:3000/; s/localhost:8888/172.19.0.4:8888/' src/main/java/com/authenticate/controller/AuthenticateController.java \
#     && sed -i 's/localhost:8888/172.19.0.4:8888/' src/main/java/com/authenticate/externalService/EmailService.java
ARG machine_ip
ENV host_ip=${machine_ip}
RUN bash change_ips.bash
RUN mvn clean package
#CMD java -jar -Djdk.util.jar.enableMultiRelease=false target/EmailService-0.0.1-SNAPSHOT.jar

FROM final
COPY --from=build ./code/src/main/resources/application.* ./jar/
COPY --from=build ./code/src/main/java/com/authenticate/controller/AuthenticateController.java ./jar/
COPY --from=build ./code/src/main/java/com/authenticate/externalService/EmailService.java ./jar/
COPY --from=build ./code/target/Authenticate-0.0.1-SNAPSHOT.jar ./jar/
WORKDIR ./jar
EXPOSE 8089
# CMD sh
CMD ["nohup","java","-jar", "-Djdk.util.jar.enableMultiRelease=false", "Authenticate-0.0.1-SNAPSHOT.jar", "&"]
