FROM maven:3.8.3-openjdk-17
COPY . ./email
RUN rm -rf /root/.m2
WORKDIR ./email
RUN microdnf install iputils procps
#RUN chmod u+x mvnw
RUN sed -i '0,/localhost/s//mongo_cont/' src/main/resources/application.properties
RUN sed -i 's/http:\/\/localhost/eureka_cont/; s/localhost/eureka_cont/' src/main/resources/application.yml
RUN mvn clean package
EXPOSE 8081
CMD bash
#CMD java -jar -Djdk.util.jar.enableMultiRelease=false target/EmailService-0.0.1-SNAPSHOT.jar
#CMD sh
#CMD ["nohup","java","-jar", "-Djdk.util.jar.enableMultiRelease=false", "EmailService-0.0.1-SNAPSHOT.jar", "&"]
